services:
  - type: web
    name: uas-paw-kelompok9-SIBEO
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: pserve src/config/production.ini
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
